//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace Sixeyed.Heartbeat.Entities
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class HeartbeatEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new HeartbeatEntities object using the connection string found in the 'HeartbeatEntities' section of the application configuration file.
        /// </summary>
        public HeartbeatEntities() : base("name=HeartbeatEntities", "HeartbeatEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new HeartbeatEntities object.
        /// </summary>
        public HeartbeatEntities(string connectionString) : base(connectionString, "HeartbeatEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new HeartbeatEntities object.
        /// </summary>
        public HeartbeatEntities(EntityConnection connection) : base(connection, "HeartbeatEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<HeartbeatLog> HeartbeatLogs
        {
            get
            {
                if ((_HeartbeatLogs == null))
                {
                    _HeartbeatLogs = base.CreateObjectSet<HeartbeatLog>("HeartbeatLogs");
                }
                return _HeartbeatLogs;
            }
        }
        private ObjectSet<HeartbeatLog> _HeartbeatLogs;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the HeartbeatLogs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToHeartbeatLogs(HeartbeatLog heartbeatLog)
        {
            base.AddObject("HeartbeatLogs", heartbeatLog);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="HeartbeatModel", Name="HeartbeatLog")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class HeartbeatLog : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new HeartbeatLog object.
        /// </summary>
        /// <param name="heartbeatLogId">Initial value of the HeartbeatLogId property.</param>
        /// <param name="heartbeatInstanceId">Initial value of the HeartbeatInstanceId property.</param>
        /// <param name="componentTypeName">Initial value of the ComponentTypeName property.</param>
        /// <param name="statusCode">Initial value of the StatusCode property.</param>
        /// <param name="logDate">Initial value of the LogDate property.</param>
        public static HeartbeatLog CreateHeartbeatLog(global::System.Int32 heartbeatLogId, global::System.Guid heartbeatInstanceId, global::System.String componentTypeName, global::System.String statusCode, global::System.DateTime logDate)
        {
            HeartbeatLog heartbeatLog = new HeartbeatLog();
            heartbeatLog.HeartbeatLogId = heartbeatLogId;
            heartbeatLog.HeartbeatInstanceId = heartbeatInstanceId;
            heartbeatLog.ComponentTypeName = componentTypeName;
            heartbeatLog.StatusCode = statusCode;
            heartbeatLog.LogDate = logDate;
            return heartbeatLog;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 HeartbeatLogId
        {
            get
            {
                return _HeartbeatLogId;
            }
            set
            {
                if (_HeartbeatLogId != value)
                {
                    OnHeartbeatLogIdChanging(value);
                    ReportPropertyChanging("HeartbeatLogId");
                    _HeartbeatLogId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("HeartbeatLogId");
                    OnHeartbeatLogIdChanged();
                }
            }
        }
        private global::System.Int32 _HeartbeatLogId;
        partial void OnHeartbeatLogIdChanging(global::System.Int32 value);
        partial void OnHeartbeatLogIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid HeartbeatInstanceId
        {
            get
            {
                return _HeartbeatInstanceId;
            }
            set
            {
                OnHeartbeatInstanceIdChanging(value);
                ReportPropertyChanging("HeartbeatInstanceId");
                _HeartbeatInstanceId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("HeartbeatInstanceId");
                OnHeartbeatInstanceIdChanged();
            }
        }
        private global::System.Guid _HeartbeatInstanceId;
        partial void OnHeartbeatInstanceIdChanging(global::System.Guid value);
        partial void OnHeartbeatInstanceIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ComponentTypeName
        {
            get
            {
                return _ComponentTypeName;
            }
            set
            {
                OnComponentTypeNameChanging(value);
                ReportPropertyChanging("ComponentTypeName");
                _ComponentTypeName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ComponentTypeName");
                OnComponentTypeNameChanged();
            }
        }
        private global::System.String _ComponentTypeName;
        partial void OnComponentTypeNameChanging(global::System.String value);
        partial void OnComponentTypeNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String StatusCode
        {
            get
            {
                return _StatusCode;
            }
            set
            {
                OnStatusCodeChanging(value);
                ReportPropertyChanging("StatusCode");
                _StatusCode = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("StatusCode");
                OnStatusCodeChanged();
            }
        }
        private global::System.String _StatusCode;
        partial void OnStatusCodeChanging(global::System.String value);
        partial void OnStatusCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> PulseTimerInterval
        {
            get
            {
                return _PulseTimerInterval;
            }
            set
            {
                OnPulseTimerIntervalChanging(value);
                ReportPropertyChanging("PulseTimerInterval");
                _PulseTimerInterval = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PulseTimerInterval");
                OnPulseTimerIntervalChanged();
            }
        }
        private Nullable<global::System.Double> _PulseTimerInterval;
        partial void OnPulseTimerIntervalChanging(Nullable<global::System.Double> value);
        partial void OnPulseTimerIntervalChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> PulseCountInterval
        {
            get
            {
                return _PulseCountInterval;
            }
            set
            {
                OnPulseCountIntervalChanging(value);
                ReportPropertyChanging("PulseCountInterval");
                _PulseCountInterval = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PulseCountInterval");
                OnPulseCountIntervalChanged();
            }
        }
        private Nullable<global::System.Int64> _PulseCountInterval;
        partial void OnPulseCountIntervalChanging(Nullable<global::System.Int64> value);
        partial void OnPulseCountIntervalChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime LogDate
        {
            get
            {
                return _LogDate;
            }
            set
            {
                OnLogDateChanging(value);
                ReportPropertyChanging("LogDate");
                _LogDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LogDate");
                OnLogDateChanged();
            }
        }
        private global::System.DateTime _LogDate;
        partial void OnLogDateChanging(global::System.DateTime value);
        partial void OnLogDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LogText
        {
            get
            {
                return _LogText;
            }
            set
            {
                OnLogTextChanging(value);
                ReportPropertyChanging("LogText");
                _LogText = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LogText");
                OnLogTextChanged();
            }
        }
        private global::System.String _LogText;
        partial void OnLogTextChanging(global::System.String value);
        partial void OnLogTextChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> TimerPulseNumber
        {
            get
            {
                return _TimerPulseNumber;
            }
            set
            {
                OnTimerPulseNumberChanging(value);
                ReportPropertyChanging("TimerPulseNumber");
                _TimerPulseNumber = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TimerPulseNumber");
                OnTimerPulseNumberChanged();
            }
        }
        private Nullable<global::System.Int32> _TimerPulseNumber;
        partial void OnTimerPulseNumberChanging(Nullable<global::System.Int32> value);
        partial void OnTimerPulseNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CountPulseNumber
        {
            get
            {
                return _CountPulseNumber;
            }
            set
            {
                OnCountPulseNumberChanging(value);
                ReportPropertyChanging("CountPulseNumber");
                _CountPulseNumber = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CountPulseNumber");
                OnCountPulseNumberChanged();
            }
        }
        private Nullable<global::System.Int32> _CountPulseNumber;
        partial void OnCountPulseNumberChanging(Nullable<global::System.Int32> value);
        partial void OnCountPulseNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> TimerMilliseconds
        {
            get
            {
                return _TimerMilliseconds;
            }
            set
            {
                OnTimerMillisecondsChanging(value);
                ReportPropertyChanging("TimerMilliseconds");
                _TimerMilliseconds = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TimerMilliseconds");
                OnTimerMillisecondsChanged();
            }
        }
        private Nullable<global::System.Double> _TimerMilliseconds;
        partial void OnTimerMillisecondsChanging(Nullable<global::System.Double> value);
        partial void OnTimerMillisecondsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> CountNumber
        {
            get
            {
                return _CountNumber;
            }
            set
            {
                OnCountNumberChanging(value);
                ReportPropertyChanging("CountNumber");
                _CountNumber = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CountNumber");
                OnCountNumberChanged();
            }
        }
        private Nullable<global::System.Int64> _CountNumber;
        partial void OnCountNumberChanging(Nullable<global::System.Int64> value);
        partial void OnCountNumberChanged();

        #endregion
    
    }

    #endregion
    
}
